config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: 'books#index'
	resources :books do
		resources :reviews
	end
	get '/books/:id', to: 'books#destroy', as: 'book_delete'
	get '/books/:book_id/reviews/:id', to: 'reviews#destroy', as: 'review_delete'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	belongs_to :category
  has_many 		:reviews
	has_attached_file :book_img, styles: { index_img: "250x250>", show_img: "400x425" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :books
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
	has_many :books,:dependent=>:destroy
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 	before_action :authenticate_user!
	before_action :find_books, only: [:show, :update, :destroy, :edit]
	def index
		if params[:category].blank?
			@books = Book.all.order('created_at DESC')
		else
			@category_id = Category.find_by(name: params[:category]).id
			@books = Book.where(:category_id => @category_id).order('created_at DESC')
		end
	end
	def new
		@book = current_user.books.build
		@categories = Category.all.map{|c| [c.name, c.id] }
	end
	def create
		@book = current_user.books.build(book_params)
		@book.category_id=params[:category_id]
		if @book.save
			redirect_to root_path
		else
			render 'new'
		end
	end
	def show
	end
	def edit
		@book_img= Book.find(params[:id])
		@categories = Category.all.map{|c| [c.name, c.id] }
		p "dfdfdfsfds"
		# @book = Book.find(params[:id])
	end
	def update
		@book.category_id=params[:category_id]
		if @book.update(book_params)
			redirect_to books_path(@book)
		else
			render 'edit'
		end
	end
	def destroy
		@book.destroy
		redirect_to root_path
	end
	private
		def book_params
			params.require(:book).permit(:title,:description,:author,:category,:book_img)
		end
		def find_books
			@book = Book.find(params[:id])
		end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book
	before_action :find_review, only: [:edit,:update,:destroy]
	def new
		@review = Review.new
	end
	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		@review.user_id = current_user.id
		p "dfdfsddfdfsds"
		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end
	end
	def review
	end
	def edit
	end
	def update
		if @review.update(review_params)
			redirect_to book_path(@book)
		else
			render 'edit'
		end	
	end
	def destroy
		@review.destroy
		redirect_to book_path(@book)
	end
	private
		def review_params
			params.require(:review).permit(:rating,:comment)
		end
		def find_book
			@book = Book.find(params[:book_id])
		end
		def find_review
			@review = Review.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<div class="container">
	<div class="panel panel-default">
		 <div class="panel-body">
				<div class="row">
					<div class="col-md-6">
						<%= simple_form_for @book , :html => {:multipart=> true } do |f| %>
							<%= f.file_field :book_img %>
							<%= select_tag(:category_id, options_for_select(@categories), :prompt=>'Select Category') %>
							<%= f.input :title, label: 'Title' %>
							<%= f.input :description, label: 'Description' %>
							<%= f.input :author, label: 'Auther' %>
							<%= f.button :submit %>
						<% end %>
					</div>
				</div>
			</div>
	</div>
</div>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= simple_form_for @book , :html => {:multipart=> true } do |f| %>
	<%= f.file_field (:book_img) %>
	<%= select_tag(:category_id, options_for_select(@categories,@book.category.id), :prompt=>'Select Category') %>
	<%= f.input :title, label: 'Title' %>
	<%= f.input :description, label: 'Description' %>
	<%= f.input :author, label: 'Auther' %>
	<%= f.button :submit %>
<% end %>

app/views/books/index.html.erb
<h1 class="text-center">List of books </h1>
<h1 class="current-category"><%= params[:category] %></h1>
<% if @books.count == 0 %>
	<h1>There are no books in the current category</h1>
<% else %>
	<% @books.each do |b| %>
		<h3><%= link_to b.title, book_path(id: b.id)%>
			<span><%=link_to (image_tag b.book_img.url(:index_img)),book_path(id: b.id) %><span>
		</h3>
	<% end %>
<%end %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>

app/views/books/show.html.erb
<h1>Show Books</h1>
<%=image_tag @book.book_img.url(:show_img)%>
<h1><%= @book.title %></h1>
<h5><%= @book.author %></h5>
<h6>Category: <%= @book.category.name %></h6>
<p><%= @book.description %></p>
<%= link_to 'Back', root_path %>
<%= link_to 'Edit', edit_book_path(@book) if current_user.id==@book.user_id%>
<%= link_to 'Delete Book',book_delete_path(@book), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } if current_user.id==@book.user_id %>
<div>
	<%= link_to 'Review', new_book_review_path(@book) %>
</div>
<div>
<h5>List of Reviews</h5>
	<% @book.reviews.each do |review| %>
		<div class="rating" data-score= <%=review.rating %>></div>
		<%= review.rating%>
		<%= review.comment%>
		<% if user_signed_in? %>
			<% if review.user_id == current_user.id %>
				<%= link_to 'Edit', edit_book_review_path(review.book,review) %>
				<%= link_to 'Delete', review_delete_path(review.book,review) , method: :delete, data: { confirm: 'Are you certain you want to delete this?' }%>
			<%end%>
		<%end%>
		<br>
	<% end %>
</div>
<script>
  $('.rating').raty({
    readOnly: true,
    start: 3,
  	path: '/assets/',
	});
</script>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="container">
   	<p>2018-19</p>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to 'Book Review', root_path, class: 'navbar-brand' %>
		</div>
		<ul class="nav navbar-nav">
			<li><%= link_to 'Sign Up', new_user_registration_path %></li>
			<% if user_signed_in? %>
				<li><%= link_to('Logout', destroy_user_session_path, method: :delete) %> </li>
			<% else %>
				<li><%= link_to('Login', new_user_session_path)  %></li>
			<% end %>
		</ul>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
				<button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Book Category
				<span class="caret"></span></button>
				<ul class="dropdown-menu" role="menu">
					<% Category.all.each do |category| %>
						<li>
							<%= link_to category.name, books_path(category: category.name), class: "link" %>
						</li>
					<% end %>
				</ul>
			</li>
			<li class="btn btn-success"><%= link_to 'Add new Book', new_book_path %></li>
		</ul>
	</div>
</nav>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<html>
	<head>
		<title>Testdemo</title>
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true%>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<%=yield %>
		<%= render "layouts/footer" %>
	</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for ([@book,@book.reviews.build]) do |f| %>
  <div id="rating-form">
  	<label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>
<script>
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/edit.html.erb
<h3>Edit Review</h3>
<%= simple_form_for ([@book,@review]) do |f| %>
  <%= f.input :rating %>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/new.html.erb
<h1>Add Reviews</h1>
<%= render 'form'%>